### ISSUE TITLE
Feature that highlights selected or hovered words is incompatible with the "Darker" mode

### ISSUE THREAD

**Issue by double-beep** [Tampermonkey/tampermonkey#1160]
For example:

![image](https://user-images.githubusercontent.com/38133098/109386289-636e4a80-7902-11eb-9de9-5a9a39a16953.png)

I am using Tampermonkey BETA version 4.12.6128

**Comment by derjanb** [comment]
I see. Please use this value at Options > Appeareance -> Custom CSS to workaround the issue for the moment:

```CSS
.darker .cm-s-default .cm-matchhighlight {
    background-color: #4b4848;
}
```
