### ISSUE TITLE
Top banner/header/margin on text editor is too big - Not enough space for text content

### ISSUE THREAD

**Issue by ozmium** [Tampermonkey/tampermonkey#495]
The extension works well, but the green header at the top of the text editor view is too big. And when combined with the document title (large font) and the black document tabs, these things take up a lot of vertical space on the page, and leave little space for the editor view content.

Please consider:

* Reduce the vertical height of the green header and the "Tampermonkey" icon at the top-left.
* Make the black tabs part of the green banner, to create more vertical space.
* Remove document title + author (underneath the tabs). It's not really needed because the document title is already partially displayed on the tab.
* Move the buttons "Search", "Replace", "Jump to Line", etc up on the same row as the other buttons.
* Remove the blank white horizontal space at the bottom of the editor view, and give more space to the editor.
* In general, try to show give much more vertical space to the text editor.

**Comment by derjanb** [comment]
Hi, please try the current beta. It removes the button and adds a menu.

Additionally, after setting "Config mode" mode to "Advanced" you can set a custom CSS rule set which is injected into the Tampermonkey extension pages. This way you can for example remove the header entirely.

**Comment by ozmium** [comment]
I don't see much difference in the beta version... Removing those buttons only has a small effect.

What about the other 5 suggestions? Especially making the green header smaller by default, and removing the document title?

Also I don't understand what you mean with the "User CSS" option or how to customize the tampermonkey page.

**Comment by derjanb** [comment]
> What about the other 5 suggestions? Especially making the green header smaller by default, and removing the document title?

I think it's OK the way it is. Especially for people that start using Tampermonkey. All others can tweak the page via "User CSS"

> Also I don't understand what you mean with the "User CSS" option or how to customize the tampermonkey page.

Please open the options page, set "Config Mode" to "Advacned", reload the page ans search for an option called "User CSS". Then please paste the code from below and press "Save". After another reload the header will be gone.

```css
.head_container { display: none !important; }
.tv_container_fit { top: 0 !important ; }
```

**Comment by ozmium** [comment]
OK thanks.

How do I collapse the bold document title + script author (text labels)?

I've tried these and they both don't work:

```css
.script_tab_head { height: 0px; }
.heading { height: 0px; }
```

**Comment by ozmium** [comment]
Update: This works on both Mozilla Firefox and Google Chrome, for Tampermonkey version 4.5:

```css
/* https://github.com/Tampermonkey/tampermonkey/issues/495 */

/* Remove top green banner/header */
.head_container { display: none !important; }
.tv_container_fit { top: 0 !important ; }

/* Move the document title up, next to the tabs */
.heading { margin-bottom: -53px; margin-left: 45px }
.author { margin-left: 640px; margin-top: -15px; font-size: 1em; }

/* Remove margin/border around the text editor area */
.editor_border { margin: 0px; }
```
