### ISSUE TITLE
Editor button toolbar

### ISSUE THREAD

**Issue by derjanb** [Tampermonkey/tampermonkey#538]
Some people are missing the editor button bar, because it saved some clicks.

That's fixed at TM BETA 4.6.5769. You have to open Tampermonkey's options page, change "Config Mode" to "Advanced", search "Appearance" -> "Custom CSS" and paste this text:

```css
.editorbuttonbar {
      display: initial;
}
```

Now press save and you'll see the button toolbar again.
