### ISSUE TITLE
[Firefox 52] Editor window is grey, unable to efid or view scripts

### ISSUE THREAD

**Issue by rychphd** [Tampermonkey/tampermonkey#833]
## Expected Behavior
When trying to Edit a script

## Actual Behavior
under the menu line "File  Edit Selection ..."
There is a thin line of white window with a bit scrollbar which would contain my script I guess, but then it's covered with grey wall -- can't see what's under

## Specifications

- Firefox ESR 52.9 32bit
- TM: 4.9.6095
- OS: Windows 7 32bit

## Script

any

**Comment by rychphd** [comment]
https://i.imgur.com/NqOv7n1.png

**Comment by derjanb** [comment]
This is a FF5x glitch, which can be fixed by adding this CSS to the "Custom CSS" setting:

```CSS
.desktop .tv_content {
display: block;
}

.editor_100 {
position: relative;
height: 99%;
}
```

**Comment by rychphd** [comment]
Nice! It worked. Thank you.

**Comment by guzszisvww** [comment]
Guys, could you please explain where the "Custom CSS" setting is?
Thanks.

**Comment by derjanb** [comment]
Simply set "Config Mode" to "Advanced" and you'll find it.

**Comment by maliayas** [comment]
> 
> 
> This is a FF5x glitch, which can be fixed by adding this CSS to the "Custom CSS" setting:
> 
> ```css
> .desktop .tv_content {
> display: block;
> }
> 
> .editor_100 {
> position: relative;
> height: 99%;
> }
> ```

This fixed "edit script" screen but broke "install script" screen. Here is the CSS that works fine for both:

````css
.desktop .tv_content[name^="tabview_contentdetails"] {
    display: block;
}
.desktop .tv_content[name^="tabview_contentdetails"] .editor_100 {
    position: relative;
    height: 99%;
}
````
