### ISSUE TITLE
Fix background color in dark mode.

### ISSUE THREAD

**Issue by RezQZiyad** [Tampermonkey/tampermonkey#898]
Hi,
![image](https://user-images.githubusercontent.com/29045522/78186273-c0504f00-746c-11ea-805d-c1880d9b2b6a.png)

 just add this to _dark.css_:
`.dark .curwaitmsg {background-color: #505050;}`

Thanks!

**Comment by Bartolomeus-649** [comment]
> just add this to _dark.css_:
> `.dark .curwaitmsg {background-color: #505050;}`

Sorry, but the setting page for scripts have the same issue.
I think the main problem is the use of `filter: invert(x)` to get dark background.It seem to work rather good for text fields, but where select/option are used, there are problems.

I use this style in the custom CCS under appearance on the settings tab, and it seems to address the issues I have seen so far.
``` css
.dark select > option {
    color: white;
    background-color: black;
}
```

As ar as I can se, this is the style that needs fixing to really solve the problem

``` css
.dark textarea, .dark input, .dark button, .dark select, .dark option {
    -webkit-filter: invert(89%);
    filter: invert(89%);
}
```
Which is defined in dark.css
